mutation updatePet($id: ID!, $name: String, $type: String, $age: Int, $neutering: Boolean, $breed: String, $sex: String) {
  updatePet(input: {id: $id, name: $name, type: $type, age: $age, neutering: $neutering, breed: $breed, sex: $sex}) {
    pet {
      id
      name
      type
      age
      neutering
      breed
      sex
    }
  }
}
